# Generated by Django 6.1 on 2026-08-29 14:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 8, 29, 14, 33, 43, 475934, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
