# Generated by Django 6.1 on 2026-08-29 23:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orderitem'),
        ('products', '0002_products_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='quantity_requestd',
            new_name='quantity_requested',
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='products.products'),
        ),
    ]
