services:


  django-web:
    build: .
    container_name: django-docker

    command:
      [
        "daphne",
        "-b",
        "0.0.0.0",
        "-p",
        "8000",
        "config.asgi:application"
      ]

    ports:
      - "8000:8000"

    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

    restart: unless-stopped

    env_file:
      - .env

    volumes:
      - .:/app

  db:
    image: postgres:17
    container_name: aforro_db

    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    restart: unless-stopped

    env_file:
      - .env

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${DB_USER} -d ${DB_NAME}"
        ]
      interval: 5s
      timeout: 5s
      retries: 5


  redis:
    image: redis:7-alpine
    container_name: aforro_redis

    ports:
      - "6379:6379"

    volumes:
      - redis_data:/data

    restart: unless-stopped

    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  celery:
      build: .
      command: celery -A config worker --loglevel=info
      depends_on:
        redis:
          condition: service_healthy
      restart: unless-stopped
      env_file:
        - .env
      volumes:
        - .:/app




volumes:
  postgres_data:
  redis_data: