# Generated by Django 6.1 on 2026-08-29 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_products_created_at'),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory', to='products.products')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory', to='store.store')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('store', 'product'), name='unique_store_item_inventory')],
            },
        ),
    ]
